### ISSUE TITLE
Support iPadOS?

### ISSUE THREAD

**Issue by chrisspiegl** [itsonlyjames/obsidian-quick-select#5]
Is there a possibility to support iPadOS?

I realize that this is tricky or maybe even useless with touch keyboards, but I use my iPad with an external keyboard as well as the MagicKeyboard Folio which function very much the same as they do on macOS, so the META + NUMBER keys would work the same way?

I think this would make Obsidian a lot more useful, thank you.

**Comment by itsonlyjames** [comment]
Thanks for bringing this scenario to my attention @chrisspiegl. 

Originally I thought of adding a setting to allow on mobile, but that would've meant it also applied to touch devices. 

Instead, I've removed the desktop only restriction, but check for the presence of a keyboard to inject functionality. 

Release v1.1.5 contains this functionality!

**Comment by chrisspiegl** [comment]
Thanks for the quick response and action.
I installed the plugin & verified that it was 1.1.5, but I could not get it to work on my iPad.
It does not show the numbers in the quick select command plate (CMD + P) and pressing META + 1/2/3 does not trigger that action.
I am not sure what kind of changes would be necessary to make it work… but I am happy to test for you if that helps to figure this out.

**Comment by itsonlyjames** [comment]
Unfortunately that means iPad does not have the keyboard navigator property. 
I had emulated mobile on desktop Obsidian but that's likely not a true simulation. 

Your involvement in testing would be great, it would mean I would not have a bunch of releases that do nothing different. 
I will attempt another fix and draft a release for you to check.

**Comment by itsonlyjames** [comment]
So there's no nice way to do this, although I have landed on, what I consider to be, a decent solution. 

Mobile, being android, iPhone, and others, are all disabled. Desktop is based on the keyboard object existing. Whereas tablet uses a new setting `Enable Quick Select for iPads/tablets`. 

Check out this pre-release: https://github.com/itsonlyjames/obsidian-quick-select/releases/tag/iPad-beta. Throw main.js and manifest.json into the quick-open plugin folder, and reload. Enable the setting, and see if it works.

Failing that, I'll add some debugging and get your to send that through. But let's see how this goes!

**Comment by chrisspiegl** [comment]
I installed the files in my plugin folder, synced to the iPad and opened Obsidian.
There, I confirmed the option "Enable for iPad" was enabled.
Opened the command plate and the numbers do not show / Meta + Number does not do anything.

On my MacBook it does work.

**Comment by itsonlyjames** [comment]
Thanks for your assistance testing this @chrisspiegl.

What I've done is simply disabled functionality on mobile, and on tablet (whcih as I found out iPad emulates Macintosh) as well as desktop. The numbers may show on tablets without keyboards, and the listener may be active, but the user cannot press meta+number unless they have a keyboard, so this may be an efficient solution. 

I've released it via [v1.1.6](https://github.com/itsonlyjames/obsidian-quick-select/releases/tag/1.1.6), update the plugin via Obsidian, have a test and let me know if it works well for you.

**Comment by chrisspiegl** [comment]
I updated my code (since I already had 1.1.6 as the version through the beta file).
Then I synced, and it works as expected and described.
Aka: the numbers are there even when no keyboard is attached (but that for me is a worth wile tradeoff).

I wonder if there is some way to tell if there is an external keyboard precent (even for iPhones). Just becuase we are on this topic; some people may use their iPhone for writing in a coffee ship and use an external keybaord… then this quick select would be powerful as well.

I care most about my iPad… so I am thankful for all the adjustments you made to support it on iPadOS. But I do have a foldable keyboard I sometimes use for my iPhone.

Anyway, all to say: right now, on iPad I see the numbers and they work as expected.
The numbers are visible when no external keyboard is connected (as described by you above).

I think this can either be closed, or kept open to improve and make it work only when an external keyboard is recognized (if such a mechanism exists in some way).

**Comment by itsonlyjames** [comment]
Thanks again for your support @chrisspiegl. I greatly appreciate your time in testing this.

I wholeheartedly agree, and I've decided while the useragent approach does in fact work, it's not an ideal solution, especially in light of the points you raise. 

I was simply disabling if any mobile presence was detected in the useragent. However I have now explored an alternative approach. 

There is no direct method for detecting the presence of a physical keyboard, however there is an experimental feature that exposes some [keyboard functionality](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard). Luckily, in Obsidian, it's a consistent rendering engine—chromium—so this will consistently return results across platforms. 

What I have attempted to do is utilise the `getLayoutMap` function to see if there is any response. If there is, then we inject the functionality, else, we do not. This _should_ mean that if you open up the quick switcher with a keyboard attached, it injects the listener. Then if you disconnect the keyboard, and open the quick switcher again, it does not inject functionality, and does not display the ordered numbers. 

Should this not work, my next idea is to attach a listener to the document for any key press, which would enable us to know if a key was pressed to open the quick switcher, thus detecting a keyboard. This approach however is not ideal again, as I would need to handle a few edge cases to clear it, so my fingers are crossed that this aforementioned approach works!

Please download the code from this beta release and test it: https://github.com/itsonlyjames/obsidian-quick-select/releases/tag/1.1.6-beta.1

**Comment by chrisspiegl** [comment]
I tested the beta, and as far as I can see the iPad does not recognize the presence of the keyboard at all again. So, not with or without the MagicKeyboard Folio. On macOS it still does show the select numbers & works.

**Thoughts:**

I have a feeling that iPadOS / iOS is not actually chromium based. If I recall correctly, on the iOS variants, the web browser thing is always Safari/WebKit based… I may be wrong about this, though. I find conflicting arguments when googling.

I tried coding a keyboard detection just in a html file with javascript & tested it on my iPad. I found out that the `navigator.keyboard.getLayoutMap` is not supported in Safari at this time on iPadOS 18.1.

The check I used:

```js
if (!navigator.keyboard || !navigator.keyboard.getLayoutMap) {
    console.warn('Keyboard Layout API is not supported in this browser.');
    document.getElementById('log').innerHTML += '\nKeyboard Layout API is not supported in this browser.'
    return false;
  }
```

**Solution Idea:**

1. Make the number display an option in the settings. User chooses to display them or not and when they are enabled, they show up no matter what.
2. Implement the Meta + Number listener no matter what (as long as the plugin is active).

This would mean: the user has control about having the numbers visible. Generally speaking, this also helps for someone who does not want the numbers but wants to keep the functionality.

And then by just having the listener, the listener will only work on `meta` `alt` + number… so it would be universal without any hoops you have to jump through.

**Comment by itsonlyjames** [comment]
That's an absolute shame. I was optimistic this approach would work. Thanks for your debugging. 

In response to your solutions, I like them. My overly-optimised brain said originally that I really didn't want to attach redundant listeners as this would be a (entirely negligable) performance hit on devices that are not utilising the plugin and would receive no extra functionality. However, to achieve the intended outcome, it is necessary. 

Now, how to go about it is the question. I think it can be evaluated through 2 lenses. Do we 
1) add a toggle for the numbers to show/hide them, or potentially look into a solution similar to [raycast](https://www.raycast.com/) (the original plugins inspiration; when you open raycast there is no numbers, it is not until you press cmd do they show up)? 
2) do we listen for a keypress upon activation of the modal, injecting the functionality and showing the numbers by default with no setting, and then when we close the modal, reset the variable assigned to `isKeyboardPresent`. This would have the added benefit of only attaching the functionality were a keyboard present. 

Either way another listener will be required, however it will be beneficial for my overly-optimised brain to only inject functionality when it can actually be utilised. 

There is also potential to rearchitect the entire plugin now I think about it.. rather than injecting the functionality when opening a modal, when I press the modifier key and a modal _is already open_, only _then_ do I inject the functionality to listen to the number pressed and select the nth item. This would mean that, on mobile etc, even if a modal is open, you can never press the meta key thus it would never inject functionality. However, if you attach a keyboard, open a modal, _then_ press the meta key, it would listen to following number... this would both appease my overly-optimised brain, as well as achieving the intended outcome to work on mobile/tablet with a keyboard. This would require the raycast approach of hiding numbers until the meta key is pressed. Following solution 1. 

I will need a bit of time to achieve this, bear with me.

**Comment by chrisspiegl** [comment]
I am looking forward to a different solution.

I like the idea to only show the numbers upon META being pressed. That sounds like it actually would solve a lot of issues.

**Comment by itsonlyjames** [comment]
I have completely re-engineered the entire plugin, removing a bunch of unecessary listeners and observers, yet retained all of the original functionality. 

Now when a modal is opened, a keypress listener is activated. Once the meta key is pressed, the numbers slide in indicating the order of results, and then once the number is selected, that item is clicked. So only on devices with keyboards that can press the meta key will receive the functionality. On mobile devices it's simply listening to keypresses that will never run true. One event listener for the functionality. Happy with that. 

Please download from this beta release and test it, let me know your thoughts. There is room for customisation on the transition, maybe no transition, fade-in-out, or slide-in-out as it currently is. Once we've solidified this I will prepare an official release!

https://github.com/itsonlyjames/obsidian-quick-select/releases/tag/1.1.6-beta.2

Edit: added transition styles to the v1.1.6-beta.2 where you can choose between "none", "fade", or "slide". The default is "slide".

**Comment by chrisspiegl** [comment]
Installed the beta and feel like this is the 2.0 version of this plugin.

Tested it on my macOS & iPadOS machine and everything was as expected.

Giving such a cool implementation which I believe to be much simpler, and great for multi device support (even supporting iPhones / Android Phones with external keyboards).

I could see one consideration to making a setting to have the numbers permanent (even when it's not supported for those who just want to see the numbers anyway).

But as it stands, I really like the “no transition” with META key version.

Great work 👍.

**Comment by itsonlyjames** [comment]
Happy to hear it exceeds your expectations! I'm also very pleased with the end result. 

I have added a permanent transition style as per your suggestion. 

Version 1.2.0 is the official release with all of this functionality!

I do expect some styling bugs with different themes due to the new counter styles, but will tackle those as they come up.

Closing this now, thanks for your assistance.

**Comment by chrisspiegl** [comment]
Wonderful. Thank you for your work on this plugin. This makes navigating the command plates much more focused when already working with the keyboard.
